/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package formulario;

import java.util.ArrayList;
import classes.*;
import javax.swing.JOptionPane;



/**
 *
 * @author rbzin
 */
public class FormAcervo extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormAcervo.class.getName());
    ArrayList<Obra> listaObra = new ArrayList();
    FormMain principal;
    
    public FormAcervo(java.awt.Frame parent, boolean modal, ArrayList<Obra> listaObras) {
        super(parent, modal);
        initComponents();
        this.listaObra = listaObras;
        principal = (FormMain) this.getParent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        taSaida = new javax.swing.JTextArea();
        inserirObra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        taSaida.setColumns(20);
        taSaida.setRows(5);
        jScrollPane1.setViewportView(taSaida);

        inserirObra.setText("Inserir Obra");
        inserirObra.addActionListener(this::inserirObraActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(inserirObra, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inserirObra, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inserirObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirObraActionPerformed
        int qtdAutores;
        Obra ob = new Obra();
        
        ob.setTitulo(JOptionPane.showInputDialog("Título:"));
        ob.setData(JOptionPane.showInputDialog("Ano de publicação:"));
        ob.setEditora(JOptionPane.showInputDialog("Editora:"));
        ob.setIsbn(JOptionPane.showInputDialog("Código ISBN:"));
        qtdAutores = Integer.parseInt(JOptionPane.showInputDialog("Quantidade de autores:"));
        
        for(int i = 0; i < qtdAutores; i++){
            Autor aut = new Autor();
            
            aut.setNome(JOptionPane.showInputDialog("Nome do Autor " + (i + 1) + ":"));
            aut.setNascionalidade(JOptionPane.showInputDialog("Nacionalidade:"));
           
            ob.setAutores(aut);
        }
        
        
        listaObra.add(ob);
        taSaida.setText("Obra cadastrada com sucesso!");
        for (Obra obr : listaObra){
            taSaida.append("\n" + obr.toString());
        }
    }//GEN-LAST:event_inserirObraActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton inserirObra;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taSaida;
    // End of variables declaration//GEN-END:variables
}
