/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package formulario;

import java.util.ArrayList;
import classes.Bibliotecaria;
import classes.Funcionario;
import java.util.EnumSet;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author eduar
 */
public class FormColaboradores extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormColaboradores.class.getName());
    final private ArrayList<Funcionario> auxiliarList;
    final private ArrayList<Bibliotecaria> bibliotecariaList;
    FormMain principal;
    
    /**
     * Creates new form FormColaboradores
     */
    public FormColaboradores(java.awt.Frame parent, boolean modal, ArrayList<Funcionario> auxList, ArrayList<Bibliotecaria> bibliotecaria) {
        this.auxiliarList = auxList;
        this.bibliotecariaList = bibliotecaria;
        
        super(parent, modal);
        initComponents();
        principal = (FormMain) this.getParent();
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        taSaida = new javax.swing.JTextArea();
        mostrarCadastrados = new javax.swing.JButton();
        appendColaborador = new javax.swing.JButton();
        bibliotecarioButao = new javax.swing.JRadioButton();
        auxButao = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        taSaida.setColumns(20);
        taSaida.setRows(5);
        jScrollPane1.setViewportView(taSaida);

        mostrarCadastrados.setText("Mostrar Funcionarios Cadastrados");
        mostrarCadastrados.addActionListener(this::mostrarCadastradosActionPerformed);

        appendColaborador.setText("Adicionar Colaborador");
        appendColaborador.addActionListener(this::appendColaboradorActionPerformed);

        buttonGroup1.add(bibliotecarioButao);
        bibliotecarioButao.setText("Bibliotecario");

        buttonGroup1.add(auxButao);
        auxButao.setSelected(true);
        auxButao.setText("Auxiliar ");

        jButton1.setText("Alterar Dados");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mostrarCadastrados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(appendColaborador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addComponent(auxButao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bibliotecarioButao, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 169, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(mostrarCadastrados, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appendColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(auxButao, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bibliotecarioButao, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarCadastradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarCadastradosActionPerformed
        if (auxButao.isSelected()){ 
            taSaida.setText(principal.showAux());
            return;
        } else if(bibliotecarioButao.isSelected()){
            taSaida.setText(principal.showBibliotecarias());
            return;
        }
    }//GEN-LAST:event_mostrarCadastradosActionPerformed

    
    
    
    private void appendColaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appendColaboradorActionPerformed
        if (auxButao.isSelected()){ 
            
            int cod = Integer.parseInt(JOptionPane.showInputDialog("Digite o codigo do Auxiliar: "));
            Funcionario funcionarioExistente = principal.acharAux(cod);
            
            if (funcionarioExistente != null){
                taSaida.setText("Auxiliar já existe cadastrado");
                taSaida.append("\n " + funcionarioExistente.toString());
                return;
            }
            
            String nome = JOptionPane.showInputDialog("Digite o nome do Auxiliar: ");
            int qntTel = Integer.parseInt(JOptionPane.showInputDialog("Quantos telefones o auxiliar possui? "));
            ArrayList<String> tel = new ArrayList();
            
            if (qntTel < 0) {
                JOptionPane.showMessageDialog(rootPane, "Número de telefone inválido! pode ser modificado depois!");
            } else if (qntTel == 0 ){
                JOptionPane.showMessageDialog(rootPane, "O número pode ser modificado depois!");
            } else{
                int cont = 0;
                while (cont < qntTel){
                    tel.add(JOptionPane.showInputDialog("Adicione o número " + (cont+1) + ": "));
                    cont ++;
                }
            }
            
            String turno = JOptionPane.showInputDialog("Digite o turno do auxiliar: ");
            
            Funcionario auxTemp = new Funcionario(cod, nome, tel, turno);
            this.auxiliarList.add(auxTemp);
            taSaida.setText("Funcionario "+ nome + " Adicionado com sucesso!");
            
            
            
        } else if(bibliotecarioButao.isSelected()){
            Bibliotecaria bibliotecariaTemp = new Bibliotecaria();
            
            String crb = JOptionPane.showInputDialog("Digite o CRB do bibliotecario: ");
            Bibliotecaria bibliotecariaExistente = principal.acharBibliotecaria(crb);
            
            
            if (bibliotecariaExistente != null){
                taSaida.setText("CRB já cadastrado no sistema tente outro!");
                taSaida.append("\n " + bibliotecariaExistente.toString());
                return;
            }
            
            bibliotecariaTemp.setCrb(crb);
            
            String nome = JOptionPane.showInputDialog("Digite o nome do Bibliotecaria: ");
            bibliotecariaTemp.setNome(nome);
            int qntTel = Integer.parseInt(JOptionPane.showInputDialog("Quantos telefones o bibliotecario possui? "));
          
            
            if (qntTel < 0) {
                JOptionPane.showMessageDialog(rootPane, "Número de telefone inválido! pode ser modificado depois!");
            } else if (qntTel == 0 ){
                JOptionPane.showMessageDialog(rootPane, "O número pode ser modificado depois!");
            } else{
                int cont = 0;
                while (cont < qntTel){
                    bibliotecariaTemp.setTelefone((JOptionPane.showInputDialog("Adicione o número " + (cont+1) + ": ")));
                    cont ++;
                }
                
            }
            
            
            bibliotecariaTemp.setTurno(JOptionPane.showInputDialog("Digite o turno do auxiliar: "));
            bibliotecariaTemp.setAreaAtuacao(JOptionPane.showInputDialog("A area de Atuação: "));
            
            
            this.bibliotecariaList.add(bibliotecariaTemp);
            taSaida.setText("Funcionario "+ nome + " Adicionado com sucesso!");
            
        }

    }//GEN-LAST:event_appendColaboradorActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton appendColaborador;
    private javax.swing.JRadioButton auxButao;
    private javax.swing.JRadioButton bibliotecarioButao;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mostrarCadastrados;
    private javax.swing.JTextArea taSaida;
    // End of variables declaration//GEN-END:variables
}
