/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formulario;
import java.util.ArrayList;
import classes.*;


/**
 *
 * @author eduar
 */
public class FormMain extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormMain.class.getName());

    /**
     * Creates new form FormMain
     */
    public FormMain() {
        initComponents();
    }
    
    final private ArrayList<Funcionario> auxList = new ArrayList();
    final private ArrayList<Bibliotecaria> bibliotecariaList = new ArrayList();
    final private ArrayList<Obra> listaObras = new ArrayList();
    final private ArrayList<FichaConservacao> fichaConservacaoList = new ArrayList();
   
    
    
    //Funções de Busca
    public Funcionario acharAux(int codInterno){
        for (Funcionario i : auxList){
            if (i.getCodInterno() == codInterno){   //Busca Funcionario Auxiliar
                return i;
            }
        }
        return null;
    }
    
    
    public Bibliotecaria acharBibliotecaria(String crb){
        for (Bibliotecaria c : bibliotecariaList){
            if(c.getCrb().equals(crb)){   //Busca bibliotecaria
                return c;
            }
        }
        return null;        
    }
    
    
    public Obra acharObra(String isbn){
        for (Obra i : listaObras){
            if (i.getIsbn().equals(isbn)){   //Busca Obra
                return i;
            }
        }
        return null;
    }
    
    
    //Funções de show
    public String showObras(){
        String msg = "Todas as Obras: ";
        
        for (Obra o : listaObras){
            msg += "\n " + o.toString();   //Mostra todas as obras cadastrada na lista
        }
        return msg;
    }
    
    
    public String showAux(){
        String msg = "Todas os auxiliares: ";
        
        for (Funcionario f : auxList){
            msg += "\n " + f.toString();   //Mostra todas os funcionario auxiliares cadastrada na lista
        }
        return msg;
    }
    
    
    public String showBibliotecarias(){
        String msg = "Todas as Bibliotecarias (o): ";

        for (Funcionario b : bibliotecariaList){
            msg += "\n " + b.toString();   //Mostra todas as bibliotecarias cadastrada na lista
        }
        return msg;
    }
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        botaoAbrirAcervo = new javax.swing.JButton();
        CadastroFichas = new javax.swing.JButton();
        VerRelatorios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Painel de administrador ");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        botaoAbrirAcervo.setText("Acervo de Obras");
        botaoAbrirAcervo.addActionListener(this::botaoAbrirAcervoActionPerformed);

        CadastroFichas.setText("Gerenciamento de Fichas de Conservação");
        CadastroFichas.addActionListener(this::CadastroFichasActionPerformed);

        VerRelatorios.setText("Ver Relatórios");
        VerRelatorios.addActionListener(this::VerRelatoriosActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VerRelatorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CadastroFichas, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                    .addComponent(botaoAbrirAcervo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(botaoAbrirAcervo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CadastroFichas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(VerRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FormColaboradores telaColaboradores = new FormColaboradores(this, true, this.auxList, this.bibliotecariaList);
        telaColaboradores.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botaoAbrirAcervoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAbrirAcervoActionPerformed
        FormAcervo telaAcervo = new FormAcervo(this, true, listaObras);
        telaAcervo.setVisible(true);
    }//GEN-LAST:event_botaoAbrirAcervoActionPerformed

    private void CadastroFichasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroFichasActionPerformed
        FormControleFichaConservacao controleFichaConservacao = new FormControleFichaConservacao(this, true, auxList, bibliotecariaList, listaObras, fichaConservacaoList);
        controleFichaConservacao.setVisible(true);

    }//GEN-LAST:event_CadastroFichasActionPerformed

    private void VerRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerRelatoriosActionPerformed
        FormRelatorio telaRelatorio = new FormRelatorio(this, true);
        
        telaRelatorio.setLocationRelativeTo(this);
        
        telaRelatorio.setVisible(true);
    }//GEN-LAST:event_VerRelatoriosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormMain().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadastroFichas;
    private javax.swing.JButton VerRelatorios;
    private javax.swing.JButton botaoAbrirAcervo;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
