/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formulario;

import classes.Obra;
import classes.Autor;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author rbzin
 */
public class FormAcervo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormAcervo.class.getName());

    /**
     * Creates new form FormObra
     */
    public FormAcervo() {
        initComponents();
    }

    ArrayList<Obra> listaObra = new ArrayList();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoInserirObra = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taSaida = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botaoInserirObra.setText("Inserir Obra");
        botaoInserirObra.addActionListener(this::botaoInserirObraActionPerformed);

        taSaida.setColumns(20);
        taSaida.setRows(5);
        jScrollPane1.setViewportView(taSaida);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(botaoInserirObra))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(botaoInserirObra)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoInserirObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoInserirObraActionPerformed
        int qtdAutores;
        Obra ob = new Obra();
        
        ob.setTitulo(JOptionPane.showInputDialog("Título:"));
        ob.setData(JOptionPane.showInputDialog("Ano de publicação:"));
        ob.setEditora(JOptionPane.showInputDialog("Editora:"));
        ob.setIsbn(JOptionPane.showInputDialog("Código ISBN:"));
        qtdAutores = Integer.parseInt(JOptionPane.showInputDialog("Quantidade de autores:"));
        
        for(int i = 0; i < qtdAutores; i++){
            Autor aut = new Autor();
            
            aut.setNome(JOptionPane.showInputDialog("Nome do Autor " + (i + 1) + ":"));
            aut.setNascionalidade(JOptionPane.showInputDialog("Nacionalidade:"));
           
            ob.setAutores(aut);
        }
        
        
        listaObra.add(ob);
        taSaida.setText("Obra cadastrada com sucesso!");
        for (Obra obr : listaObra){
            taSaida.append("\n" + obr.toString());
        }
    }//GEN-LAST:event_botaoInserirObraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormAcervo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoInserirObra;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taSaida;
    // End of variables declaration//GEN-END:variables
}
